version: "3.7"

services:

  react-frontend:
    container_name: react-frontend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true

